##  CENTOS7 JAVA
# Base operating system image based on centos 7 
FROM	centos:7


# Package installation and configuration changes
RUN 	yum install -y --setopt='tsflags=nodocs' java && yum clean all -y 
